### ISSUE TITLE
Read the whole hive 

### ISSUE THREAD

**Issue by Osrx** [ioBroker/ioBroker.node-red#30]
It would be great to be able to read not only the value of a specific counter, but also the entire device to which this counter belongs.

For example:
We have a device "Lamp" that has properties:
lamp.bright
lamp.color

And it would be possible to read all the values AND parameters of the Lamp device at once.
Let's say the node would return a string in JSON format.

The same applies to setting individual parameters for the entire device.

**Comment by mickym2** [comment]
So to create not a new enhancement - but to support this request - it would be nice if I can use wildcards in any position in the iobroker in nodes as path. In this case not only lamp.* would work also "0_userdata.0.*.lamp.*" or "0_userdata.0.+.lamp.*". Important is that these strings will be used as subscription and **not only for reading the values once.** This is  possible  with the node-list nodes now since version 2.0 - but was not possible at the time @Osrx created the request. . 

Each reading/update should create an own message. 

I **don't** think that the output should be a JSON string. I should be a simple message per value and a topic with the originating   iobroker object.  If necessary, a JSON can then be easily created by adding a JOIN and JSON Node. 

So more or less it would be great to have an iobroker in Node - which behaves like an mqtt-in Node.

**Comment by Apollon77** [comment]
@Osrx is this a possible solution?
